services:
  - type: web
    name: cotton-disease-detection
    env: python
    pythonVersion: "3.11"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
